package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

exports_files([
    "LICENSE",
])

cc_library(
    name = "base",
    hdrs = ["base.h"],
    deps = [
        "//external:glog",
        "//external:protobuf",
    ],
)
